nbproject/src/java/model/CommentCourse.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package model;

import java.sql.Date;

/**
 *
 * @author Admin
 */
public class CommentCourse {

    private User user;
    private int commentc_id;
    private int course_id;
    private int user_id;
    private String commentc_detail;
    private Date commentc_date;
    private int commentc_reply;
    private int commentc_like;
    private String commentc_image;

    public CommentCourse() {
    }

    public CommentCourse(User user, int commentc_id, int course_id, int user_id, String commentc_detail, Date commentc_date, int commentc_reply, int commentc_like) {
        this.user = user;
        this.commentc_id = commentc_id;
        this.course_id = course_id;
        this.user_id = user_id;
        this.commentc_detail = commentc_detail;
        this.commentc_date = commentc_date;
        this.commentc_reply = commentc_reply;
        this.commentc_like = commentc_like;
    }

    public CommentCourse(User user, int course_id, String commentc_detail) {
        this.user = user;
        this.course_id = course_id;
        this.commentc_detail = commentc_detail;
    }

    public CommentCourse(User user, int commentc_id, int course_id, int user_id, String commentc_detail, Date commentc_date, int commentc_reply, int commentc_like, String commentc_image) {
        this.user = user;
        this.commentc_id = commentc_id;
        this.course_id = course_id;
        this.user_id = user_id;
        this.commentc_detail = commentc_detail;
        this.commentc_date = commentc_date;
        this.commentc_reply = commentc_reply;
        this.commentc_like = commentc_like;
        this.commentc_image = commentc_image;
    }
    

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public int getCommentc_id() {
        return commentc_id;
    }

    public void setCommentc_id(int commentc_id) {
        this.commentc_id = commentc_id;
    }

    public int getCourse_id() {
        return course_id;
    }

    public void setCourse_id(int course_id) {
        this.course_id = course_id;
    }

    public int getUser_id() {
        return user_id;
    }

    public void setUser_id(int user_id) {
        this.user_id = user_id;
    }

    public String getCommentc_detail() {
        return commentc_detail;
    }

    public void setCommentc_detail(String commentc_detail) {
        this.commentc_detail = commentc_detail;
    }

    public Date getCommentc_date() {
        return commentc_date;
    }

    public void setCommentc_date(Date commentc_date) {
        this.commentc_date = commentc_date;
    }

    public int getCommentc_reply() {
        return commentc_reply;
    }

    public void setCommentc_reply(int commentc_reply) {
        this.commentc_reply = commentc_reply;
    }

    public int getCommentc_like() {
        return commentc_like;
    }

    public void setCommentc_like(int commentc_like) {
        this.commentc_like = commentc_like;
    }

    public String getCommentc_image() {
        return commentc_image;
    }

    public void setCommentc_image(String commentc_image) {
        this.commentc_image = commentc_image;
    }

    
    public String getTimediff() {
        int num = util.TimeHandle.timeDiff(this.commentc_date);
        String s;
        switch (num) {
            case 0:
                s = "Today";
                break;
            case 1:
                s = "Yesterday";
                break;
            default:
                s = num + " days ago";
        }
        return s;
    }

    @Override
    public String toString() {
        return "CommentCourse{" + "user=" + user + ", commentc_id=" + commentc_id + ", course_id=" + course_id + ", user_id=" + user_id + ", commentc_detail=" + commentc_detail + ", commentc_date=" + commentc_date + ", commentc_reply=" + commentc_reply + ", commentc_like=" + commentc_like + '}';
    }

}

nbproject/src/java/controller/user/CommentCourseServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.user;

import dal.CommentCourseDAO;
import dal.DiscussionDAO;
import model.CommentCourse;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import jakarta.servlet.http.HttpSession;
import jakarta.servlet.http.Part;
import java.util.ArrayList;
import java.util.List;
import model.Discussion;
import model.User;

/**
 *
 * @author Admin
 */
//@WebServlet(name="CommentCourseServlet", urlPatterns={"/commentc"})
public class CommentCourseServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet CommentCourseServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet CommentCourseServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        if (request.getParameter("like") != null) {
            int likenum = Integer.parseInt(request.getParameter("like"));
            CommentCourseDAO dao = new CommentCourseDAO();
            dao.rateCommentCourse(likenum);
            response.sendRedirect("discussion");
        } else {
            String courseId_raw = request.getParameter("courseId");
            int courseID = Integer.parseInt(courseId_raw);
            List<CommentCourse> list = new ArrayList<>();
            CommentCourseDAO dao = new CommentCourseDAO();
            list = dao.getCommentCourse(courseID);
            List<CommentCourse> list2 = new ArrayList<>();
            list2 = dao.getReplyCommentCourse(courseID);
            request.setAttribute("commentcourse", list);
            request.setAttribute("replycommentcourse", list2);
            request.getRequestDispatcher("/pages/user/comment/commentcourse.jsp").forward(request, response);
        }
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        Part filePart = request.getPart("upFile");
        String image;
        if (filePart == null) {
            image = "";
        } else {
            String fileName = filePart.getSubmittedFileName();
            for (Part part : request.getParts()) {
                part.write("E:\\PRJ301\\Online-Learning\\web\\upload\\" + fileName);
            }
            image = fileName;
        }
        if (request.getParameter("discussion") != null) {
            String comment = request.getParameter("discussion");
            HttpSession session = request.getSession();
            User u = (User) session.getAttribute("account");
            Discussion d = new Discussion(u, comment, image);
            DiscussionDAO dao = new DiscussionDAO();
            dao.addDiscussion(d);
            response.sendRedirect("discussion");
        } else if (request.getParameter("discusionReply") != null) {
            String reply = request.getParameter("discusionReply");
            HttpSession session = request.getSession();
            User u = (User) session.getAttribute("account");
            Discussion d = new Discussion(u, reply);
            int replyof = Integer.parseInt(request.getParameter("Replyof"));
            DiscussionDAO dao = new DiscussionDAO();
            dao.replyDiscussion(replyof, d);
            response.sendRedirect("discussion");
        }
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

nbproject/src/java/controller/user/DiscussionServlet.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/JSP_Servlet/Servlet.java to edit this template
 */
package controller.user;

import model.User;
import model.Discussion;
import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.annotation.WebServlet;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import dal.DiscussionDAO;
import jakarta.servlet.annotation.MultipartConfig;
import jakarta.servlet.http.HttpSession;
import jakarta.servlet.http.Part;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Admin
 */
@WebServlet(name = "DiscussionServlet", urlPatterns = {"/discussion"})
@MultipartConfig()
public class DiscussionServlet extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try ( PrintWriter out = response.getWriter()) {
            /* TODO output your page here. You may use following sample code. */
            out.println("<!DOCTYPE html>");
            out.println("<html>");
            out.println("<head>");
            out.println("<title>Servlet DiscussionServlet</title>");
            out.println("</head>");
            out.println("<body>");
            out.println("<h1>Servlet DiscussionServlet at " + request.getContextPath() + "</h1>");
            out.println("</body>");
            out.println("</html>");
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        if (request.getParameter("like") != null) {
            int likenum = Integer.parseInt(request.getParameter("like"));
            DiscussionDAO dao = new DiscussionDAO();
            dao.rateDiscussion(likenum);
            response.sendRedirect("discussion");
        } else {
            List<Discussion> list = new ArrayList<>();
            DiscussionDAO dao = new DiscussionDAO();
            list = dao.getDiscussion();
            List<Discussion> list2 = new ArrayList<>();
            list2 = dao.getReplyDiscussion();
            request.setAttribute("discussion", list);
            request.setAttribute("replydiscussion", list2);
            request.getRequestDispatcher("/pages/user/comment/discussion.jsp").forward(request, response);
        }

    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        Part filePart = request.getPart("upFile");
        String image;
        if (filePart == null) {
            image = "";
        } else {
            String fileName = filePart.getSubmittedFileName();
            for (Part part : request.getParts()) {
                part.write("E:\\PRJ301\\Online-Learning\\web\\upload\\" + fileName);
            }
            image = fileName;
        }
        if (request.getParameter("discussion") != null) {
            String comment = request.getParameter("discussion");
            HttpSession session = request.getSession();
            User u = (User) session.getAttribute("account");
            Discussion d = new Discussion(u, comment, image);
            DiscussionDAO dao = new DiscussionDAO();
            dao.addDiscussion(d);
            response.sendRedirect("discussion");
        } else if (request.getParameter("discusionReply") != null) {
            String reply = request.getParameter("discusionReply");
            HttpSession session = request.getSession();
            User u = (User) session.getAttribute("account");
            Discussion d = new Discussion(u, reply);
            int replyof = Integer.parseInt(request.getParameter("Replyof"));
            DiscussionDAO dao = new DiscussionDAO();
            dao.replyDiscussion(replyof, d);
            response.sendRedirect("discussion");
        }

    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}

nbproject/web/pages/user/comment/commentcourse.jsp
<%-- 
    Document   : discussion
    Created on : Jan 26, 2023, 5:05:19 PM
    Author     : Admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Online Learning</title>
        <link rel="stylesheet" href="discussion.css"/>
    </head>
    <body>

        <h2>Comment course </h2>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <div class="container bootdey">
            <div class="col-md-12 bootstrap snippets">
                <c:if test="${sessionScope.account !=null}"> 
                    <div class="panel">
                        <div class="panel-body">
                            <form action="commentc" method="post" enctype="multipart/form-data">
                                <textarea class="form-control" rows="2" placeholder="Write your comment" name="commentc"></textarea>
                                <input class="form-control" type="file" name="upFilec" >
                                <div class="mar-top clearfix">
                                    <button style="color: blue" class="btn btn-sm btn-primary " type="submit"><i class="fa fa-pencil fa-fw"></i> Post</button>
                                </div>
                            </form>
                            <script>
                                // Get a reference to our file input
                                const fileInput = document.querySelector('input[type="file"]');

                                // Create a new File object
                                const myFile = new File(['Hello World!'], 'Not found file', {
                                    type: 'text/plain',
                                    lastModified: new Date(),
                                });

                                // Now let's create a FileList
                                const dataTransfer = new DataTransfer();
                                dataTransfer.items.add(myFile);
                                fileInput.files = dataTransfer.files;

                                // Help Safari out
                                if (fileInput.webkitEntries.length) {
                                    fileInput.dataset.file = `${dataTransfer.files[0].name}`;
                                }
                            </script>
                        </div>
                    </div>
                </c:if>
                <c:forEach items="${requestScope.commentcourse}" var="i" >
                    <div class="panel">
                        <div class="panel-body">
                            <!-- Newsfeed Content -->
                            <!--===================================================-->
                            <div class="media-block">
                                <a class="media-left" href="#"><img src="src""/></a>
                                <div class="media-body">
                                    <div class="mar-btm">
                                        <a href="#" class="btn-link text-semibold media-heading box-inline">${i.user.getUser_name()}</a>
                                        <p class="text-muted text-sm"> ${i.timediff}</p>
                                    </div>
                                    <p>${i.commentc_detail}</p>
                                    <c:if test="${i.commentc_image !=  null && i.commentc_image != 'Not found file'}" >
                                        <img style="width:500px;height:400px" src="upload/${i.commentc_image}" />
                                    </c:if>
                                    <div class="pad-ver">
                                        <div class="btn-group">
                                            <a class="btn btn-sm btn-default btn-hover-success" href="discussion?like=${i.commentc_id}"><i class="fa fa-thumbs-up">${i.commentc_like}</i></a>
                                            <!--<a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>-->
                                        </div>
                                        <c:if test="${sessionScope.account !=null}">
                                            <form action="discussion" method="post" enctype="multipart/form-data">
                                                <input type="text" placeholder="Reply comment" name="discusionReply">
                                                <input type="hidden" name="Replyof" value="${i.commentc_id}">
                                                <!--<input type="file" name="upFile" >-->
                                                <input style="color: blue" type="submit" value="Send">
                                            </form>
                                        </c:if>
                                    </div>
                                    <hr>
                                    <!-- Comments -->
                                    <c:forEach items="${requestScope.replycommentcourse}" var="j">
                                        <c:if test="${j.commentc_reply== i.commentc_id}">
                                            <div>
                                                <div class="media-block">
                                                    <a class="media-left" href="#"><img src="src"/></a>
                                                    <div class="media-body">
                                                        <div class="mar-btm">
                                                            <a href="#" class="btn-link text-semibold media-heading box-inline">${j.user.getUser_name()}</a>
                                                            <p class="text-muted text-sm"> ${j.timediff}</p>
                                                        </div>
                                                        <p>${j.commentc_detail}</p>
                                                        <div class="pad-ver">
                                                            <div class="btn-group">
                                                                <a class="btn btn-sm btn-default btn-hover-success active" href="discussion?like=${j.commentc_id}"><i class="fa fa-thumbs-up">${j.commentc_like}</i> </a>
                                                            </div>  
                                                            <c:if test="${sessionScope.account !=null}">
                                                                <form action="discussion" method="post" enctype="multipart/form-data">
                                                                    <input type="text" placeholder="Reply comment" name="discusionReply">
                                                                    <input type="hidden" name="Replyof" value="${i.commentc_id}">
                                                                    <!--<input  type="file" name="upFile" >-->
                                                                    <input style="color: blue" type="submit" value="Send">
                                                                </form>
                                                            </c:if>
                                                        </div>

                                                        <hr>
                                                    </div>
                                                </div>
                                            </div>
                                        </c:if>
                                    </c:forEach>

                                </div>
                            </div>
                            <!--===================================================-->
                            <!-- End Newsfeed Content -->
                        </div>
                    </div>
                </c:forEach>
            </div>
        </div>
    </body>
</html>

nbproject/web/pages/user/comment/discussion.jsp
<%-- 
    Document   : discussion
    Created on : Jan 26, 2023, 5:05:19 PM
    Author     : Admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Online Learning</title>
        <link rel="stylesheet" href="discussion.css"/>
    </head>
    <body>

        <h2>Discusion</h2>
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <div class="container bootdey">
            <div class="col-md-12 bootstrap snippets">
                <c:if test="${sessionScope.account !=null}"> 
                    <div class="panel">
                        <div class="panel-body">
                            <form action="discussion" method="post" enctype="multipart/form-data">
                                <textarea class="form-control" rows="2" placeholder="Write your comment" name="discussion"></textarea>
                                <input class="form-control" type="file" name="upFile" >
                                <div class="mar-top clearfix">
                                    <button style="color: blue" class="btn btn-sm btn-primary " type="submit"><i class="fa fa-pencil fa-fw"></i> Post</button>
                                </div>
                            </form>
                            <script>
                                // Get a reference to our file input
                                const fileInput = document.querySelector('input[type="file"]');

                                // Create a new File object
                                const myFile = new File(['Hello World!'], 'Not found file', {
                                    type: 'text/plain',
                                    lastModified: new Date(),
                                });

                                // Now let's create a FileList
                                const dataTransfer = new DataTransfer();
                                dataTransfer.items.add(myFile);
                                fileInput.files = dataTransfer.files;

                                // Help Safari out
                                if (fileInput.webkitEntries.length) {
                                    fileInput.dataset.file = `${dataTransfer.files[0].name}`;
                                }
                            </script>
                        </div>
                    </div>
                </c:if>
                <c:forEach items="${requestScope.discussion}" var="i" >
                    <div class="panel">
                        <div class="panel-body">
                            <!-- Newsfeed Content -->
                            <!--===================================================-->
                            <div class="media-block">
                                <a class="media-left" href="#"><img src="src""/></a>
                                <div class="media-body">
                                    <div class="mar-btm">
                                        <a href="#" class="btn-link text-semibold media-heading box-inline">${i.user.getUser_name()}</a>
                                        <p class="text-muted text-sm"> ${i.timediff}</p>
                                    </div>
                                    <p>${i.discussion_detail}</p>
                                    <c:if test="${i.discussion_image !=  null && i.discussion_image != 'Not found file'}" >
                                        <img style="width:500px;height:400px" src="upload/${i.discussion_image}" />
                                    </c:if>
                                    <div class="pad-ver">
                                        <div class="btn-group">
                                            <a class="btn btn-sm btn-default btn-hover-success" href="discussion?like=${i.discussion_id}"><i class="fa fa-thumbs-up">${i.discussion_like}</i></a>
                                            <!--<a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>-->
                                        </div>
                                        <c:if test="${sessionScope.account !=null}">
                                            <form action="discussion" method="post" enctype="multipart/form-data">
                                                <input type="text" placeholder="Reply comment" name="discusionReply">
                                                <input type="hidden" name="Replyof" value="${i.discussion_id}">
                                                <!--<input type="file" name="upFile" >-->
                                                <input style="color: blue" type="submit" value="Send">
                                            </form>
                                        </c:if>
                                    </div>
                                    <hr>
                                    <!-- Comments -->
                                    <c:forEach items="${requestScope.replydiscussion}" var="j">
                                        <c:if test="${j.discussion_reply== i.discussion_id}">
                                            <div>
                                                <div class="media-block">
                                                    <a class="media-left" href="#"><img src="src"/></a>
                                                    <div class="media-body">
                                                        <div class="mar-btm">
                                                            <a href="#" class="btn-link text-semibold media-heading box-inline">${j.user.getUser_name()}</a>
                                                            <p class="text-muted text-sm"> ${j.timediff}</p>
                                                        </div>
                                                        <p>${j.discussion_detail}</p>
                                                        <div class="pad-ver">
                                                            <div class="btn-group">
                                                                <a class="btn btn-sm btn-default btn-hover-success active" href="discussion?like=${j.discussion_id}"><i class="fa fa-thumbs-up">${j.discussion_like}</i> </a>
                                                            </div>  
                                                            <c:if test="${sessionScope.account !=null}">
                                                                <form action="discussion" method="post" enctype="multipart/form-data">
                                                                    <input type="text" placeholder="Reply comment" name="discusionReply">
                                                                    <input type="hidden" name="Replyof" value="${i.discussion_id}">
                                                                    <!--<input  type="file" name="upFile" >-->
                                                                    <input style="color: blue" type="submit" value="Send">
                                                                </form>
                                                            </c:if>
                                                        </div>

                                                        <hr>
                                                    </div>
                                                </div>
                                            </div>
                                        </c:if>
                                    </c:forEach>

                                </div>
                            </div>
                            <!--===================================================-->
                            <!-- End Newsfeed Content -->
                        </div>
                    </div>
                </c:forEach>
            </div>
        </div>
    </body>
</html>